name: Test

on: [push, pull_request]

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    
    - name: Test
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go test -v ./...
